### ISSUE TITLE
Camera capture frame

### ISSUE THREAD

**Issue by juliodinizperdigao** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#431] opened 2018-02-24 17:06 UTC
We are developing an image reco app, with Clarifai library. The app needs capture frame in some interval defined by us. We know that's is possible with takePicture function with setInterval defined. But this function will play a sound every time a picture is taken. It's possible to capture without a sound?

Any help?
Thanks!

**Comment by Choppel** [comment] 2018-02-25 10:32
Hi @juliodinizperdigao 
this has been asked multiple times and the answer is no (see #408 and #214).

For Android this would technically be possible (see luispimenta's threads in #214) He made an own fork of cordova-plugin-camera-preview to turn off the shutter sound for iOS and Android.

As for iOS, it is clearly stated in the "Apple Developer Program License Agreement" section 3.3.8 that " a reasonably conspicuous audio, visual or other indicator must be displayed to the user as part of the Application to indicate that a Recording is taking place".

So IMO the solution by luispimenta is a direct violation of the terms and agreements and can therefore not be integrated in this plugin.

But feel free to try his fork :)

**Comment by westonganger** [comment] 2018-02-25 15:42
Based on the amount of interest I'm willing to consider a PR for silencing Android shutter sounds.

**Comment by juliodinizperdigao** [comment] 2018-02-25 19:00
Hi @Choppel ,
recently I tried the respository of luispimenta, but it's getting error with Eclipse.

About the violation of the terms, how some companies has developed apps which make recognition with camera opened. One of these companies are Catchoom. Their plugin open the camera, scan picture and send to the server to make recognition.

Thanks!

**Comment by Choppel** [comment] 2018-03-09 15:51
@juliodinizperdigao 
Maybe Catchoom does have a feedback. I don't know. However, if Catchoom takes a picture without informing the user about it (via audio, visual or other output), it is a direct violation of the iOS terms nonetheless. The fact that an app that does not comply but that also does not get pulled off the shop is just pure luck.

@luispimenta
I seems you solved the disabling of the shutter sound for both iOS and Android. Could you please create a PR for that?

**Comment by westonganger** [comment] 2018-03-14 18:04
Duplicate of #408 and #214. Closing in lieu of those

**Closed by westonganger** 2018-03-14 18:04 UTC
