### ISSUE TITLE
IOS and Android Video and multiple pictures 

### ISSUE THREAD

**Issue by KamranAliKhan01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#139] opened 2016-10-22 11:01 UTC

**Comment by westonganger** [comment] 2017-03-01 15:56
Video would be a nice to have feature. Multiple pictures will be possible once base64 photo taking is added. PR's are welcome. Closing as this is a duplicate of other issues.

**Closed by westonganger** 2017-03-01 15:56 UTC
