### ISSUE TITLE
getSupportedFocusModes return no camera

### ISSUE THREAD

**Issue by sikucing** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#389] opened 2017-11-23 16:21 UTC
hi, i use this code to test camera preview in my Xiaomi redmi 3s prime (Marshmallow)
```
initializeCamera() {
    let cameraOpts:CameraPreviewOptions = {
      x: 0,
      y: 0,
      width: window.innerWidth,
      height: window.innerHeight,
      camera: 'back',
      tapPhoto: false,
      previewDrag: false,
      toBack: false,
      alpha: 1
    };

    this.cameraPreview.startCamera(cameraOpts)
      .then((res)=> {
        return this.cameraPreview.getSupportedFocusModes();
      })
      .then((res)=> {
        console.log(res)
      })
      .catch((err)=>console.log(err));
  }
```
the camera preview is running fine, but when i want to check the supported focus mode or set focus mode to whatever is defined in readme i always get error 'no camera'. 
is there anything wrong in my line of code?

**Comment by Choppel** [comment] 2017-11-24 15:04
Hi sicuking,
although your code seems to be specifically for ionic I managed to reproduce your problem. It seems the startCamera function success callback gets called too soon so the whatever you call afterwards will throw "no camera" (tried it at least with getSupportedFlashModes and getSupportedFocusModes).

You should wrap the call of getSupportedFocusModes in a setTimeout call until this is fixed. See the example below (without promises because the plugin does not support it directly...but you'll get the idea :)
```javascript
CameraPreview.startCamera({
    x: 0,
    y: 0,
    width: window.innerWidth,
    height: window.innerHeight,
    camera: 'back',
    tapPhoto: false,
    previewDrag: false,
    toBack: false,
    alpha: 1
}, () => {
    setTimeout(() => {
        CameraPreview.getSupportedFocusModes((_modes) => {
            console.log(_modes);
        }, (_error) => {
            console.error('supported focus modes could not be retrieved. ' + _error);
        });
    }, 1000);
}, (_error) => {
    console.error('camera could not be started. ' + _error);
});

**Comment by sikucing** [comment] 2017-11-25 15:11
it works...
thanks @Choppel

**Comment by Choppel** [comment] 2017-11-28 07:12
@sikucing Good to hear :)
Please close this ticket.

**Comment by westonganger** [comment] 2017-11-28 14:38
@Choppel thanks for your hard work triaging issues. Closed

**Closed by westonganger** 2017-11-28 14:38 UTC
