### ISSUE TITLE
Camera preview in tabs (ionic 3)

### ISSUE THREAD

**Issue by hyoungbin** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#357] opened 2017-09-12 02:44 UTC
hi i'm making an app using ionic and cordova. 
especially cordova camera preview plugin. 
my app has 3 tabs and i want to put camera preview one of 3 tabs. 

my camera tab,

    export class CameraPage {
    
      constructor(private platform : Platform, public navCtrl: NavController, public navParams: NavParams, private cameraPreview: CameraPreview) {
        this.platform.ready().then(()=> {
          let options = {
            x: 0,
            y: 0,
            width: window.screen.width,
            height: window.screen.height,
            camera: 'rear',
            tapPhoto: true,
            previewDrag: true,
            toBack: true,
          }
          this.cameraPreview.startCamera(options).then(
            (res)=> {
              console.log(res)
            },
            (err) => {
              console.log(err)
            });
        })
      }
    
    
      ionViewDidLoad() {
        console.log('ionViewDidLoad CameraPage');
      }

and at the bottom of the "src/theme/variables.scss" file

    $background-color: transparent;

"src/app/app/scss" file
```
html, body, .ion-app, .ion-content {
  background-color: transparent;
}
```

when i text the app in my iphone, 
console says

ionViewDidLoad MainTabsPage
ionViewDidLoad CameraPage
Ionic Native: deviceready event fired after 1396 ms
Camera already started!

and then screen doesn't show. 
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Fdt3Y.jpg

my info : 
cli packages:

    @ionic/cli-utils  : 1.6.0 
    ionic (Ionic CLI) : 3.6.0 
global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 2.1.4
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.2 
    npm        : 5.4.1 

1. i don't figure out why my console says "Camera already started"
2. i don't know why the screen is black. I made my background-color transparent

**Comment by SkogDev** [comment] 2017-09-12 05:46
Does this css help?

`html, body, ion-app, div.nav-decor, .ion-content, .app-root {
    background-color: transparent !important;
  }`

**Comment by hyoungbin** [comment] 2017-09-12 07:14
@SkogDev  finally I solved the problem Thanks!!!!

**Comment by oricoh** [comment] 2017-09-28 15:51
Doesn't work for me and the CSS suggestion doesn't work. Any other ideas?

**Comment by Choppel** [comment] 2017-11-29 14:17
@oricoh 
Hi,
please post some example source code to show what exactly does not work. Maybe the source of the problem is a complete different one.

regards Choppel

**Comment by abanoubsamaan** [comment] 2017-12-13 19:48
i have solved the same issue by doing this
`.nav-decor,ion-app{
    background-color: transparent !important; 
}`

**Comment by Choppel** [comment] 2017-12-18 10:20
@hyoungbin 
Please close this issue. It's resolved.

**Closed** 2017-12-18 11:27 UTC
