### ISSUE TITLE
ToBack doesn't work

### ISSUE THREAD

**Issue by sourcer18** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#603] opened 2020-04-25 10:13 UTC
ToBack doesn't work, I've added the styles too, and the camera is always ahead. Is there something I am not considering or is it not working?

![image](https://user-images.githubusercontent.com/6040292/80277199-add4d880-86ed-11ea-86e2-8647aa88c997.png)

![614280ad-4b7f-49f3-bda8-8063c74d0606](https://user-images.githubusercontent.com/6040292/80277716-3739da00-86f1-11ea-8b42-30c6e7813906.jpg)

**Comment by harryt2** [comment] 2020-05-13 17:16
I'm also having this problem. I open the view that calls the camera, and it sits on top of everything. The strange thing is, when I hit back (on Android) re-open the view, toBack works. It's just on the first open that it's not working.

**Comment by sourcer18** [comment] 2020-05-13 20:15
Well if you get something warn, because I still have not achieved anything: S

**Comment by harryt2** [comment] 2020-05-13 20:29
Sure, I made a workaround. See my answer on this thread

https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/601

**Comment by smallmonke** [comment] 2020-06-03 06:26
我是17年用的 现在还是这样的吗？但是我看到cordova-plugin-camera是不是可以再底部了

**Comment by westonganger** [comment] 2020-06-24 14:42
Your going to have to play around with your CSS to achieve this. Sometimes it can be tricky. Closing as its a duplicate of many other issues.

**Closed by westonganger** 2020-06-24 14:42 UTC

**Comment by Smiley3112** [comment] 2020-06-26 13:20
> Your going to have to play around with your CSS to achieve this. Sometimes it can be tricky. Closing as its a duplicate of many other issues.

I'm not sure how changing any CSS is going to fix this? The camera preview is sitting infront of the webview, so no CSS is going to fix that?

**Comment by ryaa** [comment] 2020-07-09 06:57
If you use capacitor then this is a known limitation - see https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/601#issuecomment-655939195
