### ISSUE TITLE
App crashes on iOS when 20 to 25 successive images are captured

### ISSUE THREAD

**Issue by Tawsif** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#162] opened 2017-02-06 07:01 UTC
Hi I have a problem when I capture multiple times ie. 20 to 25 times approx. then it crashes on iPhone 6 plus

**Comment by erperejildo** [comment] 2017-02-06 10:23
Can you share your code?

**Comment by Tawsif** [comment] 2017-02-06 11:25
I have used https://github.com/westonganger/cordova-plugin-camera-preview plugin for phonegap development.

When I build the app for iOS Platform and capture 25 images from camera by using takePicture method it crashes.

**Comment by erperejildo** [comment] 2017-02-06 12:12
Not sure about that one. Try this version on master and share at least you takePicture function

**Comment by Tawsif** [comment] 2017-02-06 12:47
@erperejildo following is my takepicture function:

- (void) invokeTakePicture:(CGFloat) maxWidth withHeight:(CGFloat) maxHeight {
@autoreleasepool {
        AVCaptureConnection *connection = [self.sessionManager.stillImageOutput connectionWithMediaType:AVMediaTypeVideo];
        [self.sessionManager.stillImageOutput captureStillImageAsynchronouslyFromConnection:connection completionHandler:^(CMSampleBufferRef sampleBuffer, NSError *error) {
 
 
                 NSLog(@"Done creating still image");
				 
				 if (error) {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
						 
                 } else {
				 
					@try {
					
					
					
					if(self.sessionManager != nil) {
					
					if(CMSampleBufferIsValid(sampleBuffer)){

					
							NSData *imageData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:sampleBuffer];
							UIImage *capturedImage  = [[UIImage alloc] initWithData:imageData];						 
							capturedImage = capturedImage.fixOrientation;		
							NSData *finalImageData = UIImageJPEGRepresentation(capturedImage, 0.0);							
						
						
							NSString *temporaryFileName = [NSProcessInfo processInfo].globallyUniqueString;
							NSString *temporaryFilePath = [NSTemporaryDirectory() stringByAppendingPathComponent:[temporaryFileName stringByAppendingPathExtension:@"jpg"]];
						 
							[finalImageData writeToFile:temporaryFilePath atomically:YES];
							
							//NSString *temporaryFilePath = [finalImageData base64EncodedStringWithOptions:0];
							
							CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:temporaryFilePath];
							[pluginResult setKeepCallbackAsBool:true];
							[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
					
							}
							else {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
							}
							
							

							
							
							}
							else {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
							}
							

						}								                
						@catch (NSException *exception) {
							NSString *temporaryFilePath = [NSString stringWithFormat:@"%@",[exception reason]];
							CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:temporaryFilePath];
							[pluginResult setKeepCallbackAsBool:true];
							[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
						}
			
					}
							//CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Welcome"];
							//[pluginResult setKeepCallbackAsBool:true];
							//[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
				 
         }];
	}	 
}

**Comment by Tawsif** [comment] 2017-02-06 12:48
@erperejildo following is my takepicture function:

`- (void) invokeTakePicture:(CGFloat) maxWidth withHeight:(CGFloat) maxHeight {
@autoreleasepool {
        AVCaptureConnection *connection = [self.sessionManager.stillImageOutput connectionWithMediaType:AVMediaTypeVideo];
        [self.sessionManager.stillImageOutput captureStillImageAsynchronouslyFromConnection:connection completionHandler:^(CMSampleBufferRef sampleBuffer, NSError *error) {
 
 
                 NSLog(@"Done creating still image");
				 
				 if (error) {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
						 
                 } else {
				 
					@try {
					
					
					
					if(self.sessionManager != nil) {
					
					if(CMSampleBufferIsValid(sampleBuffer)){

					
							NSData *imageData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:sampleBuffer];
							UIImage *capturedImage  = [[UIImage alloc] initWithData:imageData];						 
							capturedImage = capturedImage.fixOrientation;		
							NSData *finalImageData = UIImageJPEGRepresentation(capturedImage, 0.0);							
						
						
							NSString *temporaryFileName = [NSProcessInfo processInfo].globallyUniqueString;
							NSString *temporaryFilePath = [NSTemporaryDirectory() stringByAppendingPathComponent:[temporaryFileName stringByAppendingPathExtension:@"jpg"]];
						 
							[finalImageData writeToFile:temporaryFilePath atomically:YES];
							
							//NSString *temporaryFilePath = [finalImageData base64EncodedStringWithOptions:0];
							
							CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:temporaryFilePath];
							[pluginResult setKeepCallbackAsBool:true];
							[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
					
							}
							else {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
							}
							
							

							
							
							}
							else {
								CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Camera not started"];
								[pluginResult setKeepCallbackAsBool:true];
								[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
							}
							

						}								                
						@catch (NSException *exception) {
							NSString *temporaryFilePath = [NSString stringWithFormat:@"%@",[exception reason]];
							CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:temporaryFilePath];
							[pluginResult setKeepCallbackAsBool:true];
							[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
						}
			
					}
							//CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Welcome"];
							//[pluginResult setKeepCallbackAsBool:true];
							//[self.commandDelegate sendPluginResult:pluginResult callbackId:self.onPictureTakenHandlerId];
				 
         }];
	}	 
}`

**Comment by erperejildo** [comment] 2017-02-06 13:37
I wanted to mean something like this:
`cordova.plugins.camerapreview.takePicture({maxWidth:640, maxHeight:640});`

**Comment by Tawsif** [comment] 2017-02-07 04:23
@erperejildo thanks for clarification.

My **startCamera** method call is as follows:

```
cordova.plugins.camerapreview.startCamera({ x: cameraX, y: cameraY, width: (_cameraWidth), height: (_cameraHeight) }, "back", _tapEnabled, _dragEnabled, _toBack);

where, cameraX=0;
cameraY=0;
_cameraWidth= **_calculateAspectRatioFit**(2448, 3264, screen.width, screen.height);  // is calculated according to aspect ratio
_cameraHeight= **_calculateAspectRatioFit**(2448, 3264, screen.width, screen.height); is calculated according to aspect ratio
_tapEnabled=false;
_dragEnabled=false;
_toBack=true;
```

**Calculate Aspect Ratio Method**

`/**
             * Conserve aspect ratio of the orignal region. Useful when shrinking/enlarging
             * images to fit into a certain area.
             *
             * @param {Number} srcWidth Source area width
             * @param {Number} srcHeight Source area height
             * @param {Number} maxWidth Fittable area maximum available width
             * @param {Number} maxHeight Fittable area maximum available height
             * @return {Object} { width, heigth }
        */
        function **_calculateAspectRatioFit**(srcWidth, srcHeight, maxWidth, maxHeight) {

            var ratio = Math.min(maxWidth / srcWidth, maxHeight / srcHeight);

            return { width: srcWidth * ratio, height: srcHeight * ratio };
        }  `

**And take picture method call is as follows**

`cordova.plugins.camerapreview.takePicture();`

**Comment by erperejildo** [comment] 2017-02-07 10:00
The startCamera looks ok, as well the other one but I expected some issues with takePicture with no defined sizes or higher than 1500. You are taking pictures with your native resolution and this can cause some problems. Try using takePicture({maxWidth:800, maxHeight:800}).

Unfortunately we are working with hybrid apps and the performance can't be perfect I'm afraid (but that doesn't mean that can't be improvable)

**Comment by Tawsif** [comment] 2017-02-07 10:32
@erperejildo thanks for your reply I will try for your solution, Actually I dont have any issue with performance, but the crashing of app is an issue which I think is not acceptable.

I cannot understand why we cannot apply sizes greater than 1500 ? How is it related to crash ?

Also I have few queries can you please answer those? What do you think does any of the below mentioned points plays role in the crash ??

1) Are there any memory leaks in the code ?
2) Using a high resolution preset, ie. **AVCaptureSessionPresetPhoto** can this create a crash ?
3) Are there any of the iOS 10 memory leaks ?

**Comment by erperejildo** [comment] 2017-02-07 10:59
Not sure about why it crashes, can't help you with any of those questions, sorry. I have no idea about Java to be honest.
Also I haven't tried on IOS yet but I did not have any problems with performance, just with big pictures.

Further info:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/158

**Comment by Tawsif** [comment] 2017-02-07 12:41
@erperejildo However `takePicture({maxWidth:800, maxHeight:800})` this also did not work.

I will be waiting for any updates on this.

**Comment by erperejildo** [comment] 2017-02-07 13:14
Are you adding the whole thing?
`cordova.plugins.camerapreview.takePicture({maxWidth:800, maxHeight:800});
`

**Comment by Tawsif** [comment] 2017-02-07 13:24
Yes I added the whole thing, but that made no change to my issue. App still crash on more than 25 capture attemtps.

You can try on your side too.

**Comment by erperejildo** [comment] 2017-02-07 13:37
I'll do today later on a PR from this other repository to fix some issues:
https://github.com/techieyann/CordovaCameraPreview

Could you try that one in order to see if you have the same issue using than one?

**Comment by Tawsif** [comment] 2017-02-07 13:40
Yes sure I will try it and report to you tomorrow

**Comment by Tawsif** [comment] 2017-02-08 05:44
Hi @erperejildo 

https://github.com/techieyann/CordovaCameraPreview also didn't work for me.

It also crashes the same way.

**Comment by erperejildo** [comment] 2017-02-08 09:15
Ok thanks for letting me know.

I'm afraid I can't help you with this then. We'd have to wait till someone can fix this. Sorry :(

**Comment by westonganger** [comment] 2017-04-29 17:34
Duplicate of #200

**Closed by westonganger** 2017-04-29 17:34 UTC

**Comment by ryaa** [comment] 2020-04-29 05:35
This problem could be related to https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/604
