### ISSUE TITLE
error: "plugin_not_installed" when invoking startCamera method

### ISSUE THREAD

**Issue by Ruan20795** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#457] opened 2018-05-30 22:17 UTC
I am having issues using this plugin and I cannot find the solution to what I might be doing wrong.

I have installed the plugin using the traditional method as described on [ionicframework](https://ionicframework.com/docs/native/camera-preview/), as well as on the [ionicframework forum](https://forum.ionicframework.com/t/ionic-3-camerapreview-startcamera-returns-plugin-not-installed/85947/2) but with no luck.

# Ionic Environment:

### cli packages:
- **ionic/cli-utils**  : 1.19.2
- **ionic (Ionic CLI)** : 3.20.0

### global packages:
- **cordova (Cordova CLI)** : 8.0.0

### local packages:
- **ionic/app-scripts** : 3.1.9
- **Cordova Platforms**  : android 7.0.0
- **Ionic Framework**    : ionic-angular 3.9.2

### System:
- **Android SDK Tools** : 25.2.5
- **Node**              : v10.1.0
- **npm**               : 5.6.0
- **OS**                : Windows 10

# config.xml
`<plugin name="cordova-plugin-camera-preview" spec="^0.9.0" />`
Also Tried
`<plugin name="cordova-plugin-camera-preview" spec="git+https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git" />`

# package.json
`"cordova-plugin-camera-preview": "^0.9.0"`
Also Tried
`"cordova-plugin-camera-preview": "git+https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git"`

# Plugin Usage
```
import { Component, OnInit } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { SplashScreen } from '@ionic-native/splash-screen';

import { Camera, CameraOptions } from '@ionic-native/camera';
import { LoadingController } from 'ionic-angular';
import { AlertController } from 'ionic-angular';
import { ToastController } from 'ionic-angular';
import { Storage } from '@ionic/storage';

import { Badge } from '@ionic-native/badge';
import { Insomnia } from '@ionic-native/insomnia';
import { CameraPreview, CameraPreviewPictureOptions, CameraPreviewOptions, CameraPreviewDimensions } from '@ionic-native/camera-preview';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  styles: ['home.scss']
})
export class HomePage implements OnInit {
  //==========Constructor==========//
  constructor(public navCtrl: NavController,
    private camera: Camera,
    public loadingCtrl: LoadingController,
    public alertCtrl: AlertController,
    public toastCtrl: ToastController,
    private http: HttpClient,
    private storage: Storage,
    private badge: Badge,
    private insomnia: Insomnia,
    private splashScreen: SplashScreen,
    private cameraPreview: CameraPreview,
    public platform: Platform)
  {
    this.splashScreen.show();

    this.insomnia.keepAwake()
      .then(
        () => console.log('success'),
        () => console.log('error')
      );
      
      let cameraPreviewOpts: CameraPreviewOptions = {
        x: 0,
        y: 0,
        width: window.screen.width,
        height: window.screen.height,
        camera: 'rear',
        tapPhoto: true,
        previewDrag: true,
        toBack: true,
        alpha: 1
      };

      this.platform.ready().then(() => {
        this.cameraPreview.startCamera(cameraPreviewOpts).then(
          (res) => {
            console.log(res);
            this.cameraPreview.show();
          },
          (err) => {
            console.log(err);
            alert(JSON.stringify(err));
          });
      });
  }
  //===============================//
}
```

I understand this is still in beta phase, but please can someone help with this issue since my whole app model is built around this idea.

**Comment by westonganger** [comment] 2018-06-13 16:04
Closing as this is not a bug with the plugin. Please troubleshoot your own app specific configuration and quirks.

**Closed by westonganger** 2018-06-13 16:04 UTC

**Comment by rrath-edr** [comment] 2018-11-06 18:39
@Ruan20795 Hi I am facing the same issue. Were you able to resolve the issue?

**Comment by Ruan20795** [comment] 2018-11-08 19:57
@rrath-edr after countless hours of struggle, I managed to resolve this issue. I am not 100% sure what caused the issue but the main culprit seemed to be the fact that I always served my app and never used the run command to test my app. For some reason the Camera Preview seems to struggle while serving your app. With this said, I know that the Camera Preview Plugin has been updated with code changes and bug fixes so that issue might have been resolved. I also ended up writing a similar copy of the Camera Preview Plugin as I had to implement ML with image processing, you can check out my implementation at https://play.google.com/store/apps/details?id=dev.frugily.ionic&hl=en_ZA.

I am also in the process of rewriting the Camera Preview entirely as I the Camera Preview Plugin is not meant for image processing ML.

Hope this helps you :)

**Comment by kjellouli** [comment] 2019-07-09 00:24
Spent hours on this to realize that it doesn't work on devapp as mentioned on https://ionicframework.com/docs/appflow/devapp/, will see if it does on other platforms

**Comment by Georgetxm** [comment] 2019-12-17 14:19
@Ruan20795 Hey man, I am using this module for ML Image processing as well, am currently having issues with this plugin. Would like to know the limitations of it. Also, how is the progress of your rewritten plugin?
